ModacTestRunner: Make it possible to queue wikis.
Also do not set variables in blocks.

Ticket: #4495

diff --git a/test/unit/ModacTestRunner/runtests b/test/unit/ModacTestRunner/runtests
--- a/test/unit/ModacTestRunner/runtests
+++ b/test/unit/ModacTestRunner/runtests
@@ -49,52 +49,56 @@ outlock="$ourtemp/output.lock" # synchronizes output to STDOUT
 
 # wikis to test
 test -z "$wikis" && wikis="$defaultwikis"
+# reformat "browser1, browser2" -> "browser1 , browser2" for for-loop
+# finish with "," so it waits for all tests to finish
+wikis="`echo "$wikis" | sed -e 's# *, *# , #g'` ,"
 
 # run tests
 for eachwiki in $wikis; do
-    # run each browser in parallel
-    ( flock -s 200
-        cd "$wikidir/$eachwiki/test/unit" || exit 1
-        logfile="$ourtemp/${eachwiki}.log"
-        failedtests=""
+    test "$eachwiki" = ',' && {
+        # join testruns
+        flock -x "$lock" echo -e "\nBatch finished\n"
+    } || {
+        # run each browser in parallel
+        ( flock -s 200
+            cd "$wikidir/$eachwiki/test/unit" || exit 1
+            logfile="$ourtemp/${eachwiki}.log"
+            failedtests=""
 
-        # find plugins to test (if not provided via cli)
-        test -z "$plugins" && {
-            plugins=`find -L . -maxdepth 2 -mindepth 1 -name qwikitest | sed -n 's#\./\(.*\)/qwikitest#\1#p'`
-        }
-
-        # run actual tests
-        for eachtest in $plugins; do
-            FOSWIKI_ASSERTS=1 ../bin/TestRunner.pl "$eachtest" >> "$logfile" 2>&1 || failedtests="$failedtests '$eachtest'"
-        done;
-
-        # print result to STDOUT / cleanup our logfile
-        ( flock -x 300 # only one output at a time
-            test -n "$failedtests" && {
-                echo "$eachwiki: $failedtests" >> "$failedlog"
+            # find plugins to test (if not provided via cli)
+            test -z "$plugins" && {
+                plugins=`find -L . -maxdepth 2 -mindepth 1 -name qwikitest | sed -n 's#\./\(.*\)/qwikitest#\1#p'`
             }
-            echo "Results from $eachwiki:"
-            cat "$logfile"
-            rm "$logfile"
-        )300>"$outlock"
-    )200>"$lock"&
-    sleep 1; # let those tests be a little bit unsynchronized
+
+            # run actual tests
+            for eachtest in $plugins; do
+               FOSWIKI_ASSERTS=1 ../bin/TestRunner.pl "$eachtest" >> "$logfile" 2>&1 || failedtests="$failedtests '$eachtest'"
+            done;
+
+            # print result to STDOUT / cleanup our logfile
+            ( flock -x 300 # only one output at a time
+                test -n "$failedtests" && {
+                    echo "$eachwiki: $failedtests" >> "$failedlog"
+                }
+                echo "Results from $eachwiki:"
+                cat "$logfile"
+                rm "$logfile"
+            )300>"$outlock"
+        )200>"$lock"&
+        sleep 1; # let those tests be a little bit unsynchronized
+    }
 done
 
 # output result
-( flock -x 400
-    test -e "$failedlog" && {
-        echo
-        echo "failed tests:"
-        cat "$failedlog"
-        rm "$failedlog"
-        fail=1
-    } || {
-        echo
-        echo "all tests passed"
-        fail=0
-    }
-)400>"$lock"
+test -e "$failedlog" && {
+    echo "failed tests:"
+    cat "$failedlog"
+    rm "$failedlog"
+    fail=1
+} || {
+    echo "all tests passed"
+    fail=0
+}
 
 # cleanup
 rm "$lock" "$outlock"
